sudo: required

language: generic

services:
  - docker

cache:
  directories:
    - "node_modules"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  # - sudo apt-get install -y python2.7

install:
  # Install Ansible.
  - sudo pip install ansible
  # Install sshpass
  - sudo apt-get install -y sshpass

script:
    - npm install
    - npm test
    - npm run build

deploy:
  - provider: script
    script: bash deploy.sh stable
    on:
      branch: master
  - provider: script
    script: bash deploy.sh beta
    on:
      branch: beta
