sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

script:
    - npm install
    - npm test
    - npm run build
    - docker build --tag "$IMAGE_NAME" .

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
