sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  # Install Ansible.
  - pip install ansible

script:
    - npm install
    - npm test
    - npm run build

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
