sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache:
  directories:
    - "node_modules"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - sudo pip install ansible
  # Install sshpass
  - sudo apt-get install -y sshpass

script:
    - npm install
    - npm test
    - npm run build

deploy:
  provider: script
  script: bash deploy.sh latest
  on:
    branch: master

deploy:
  provider: script
  script: bash deploy.sh beta
  on:
    branch: beta
