- name: "Pull docker image for Production"
  become: True
  docker_image:
    name: erchiragjain92/node-test-app
    tag: stable
  when: deploy_env == "stable"

- name: "Pull docker image for Beta"
  become: True
  docker_image:
    name: erchiragjain92/node-test-app
    tag: beta
  when: deploy_env == "beta"
