- name: Install python-pip
  become: True
  apt:
     name: python-pip

- name: Install python dependency
  become: True
  pip:
     name: docker

- name: Install Ansible.
  become: True
  pip:
     name: ansible
