- name: "Start the container for Production"
  become: True
  docker_container:
    name: test_stable
    image: "erchiragjain92/node-test-app:stable"
    ports:
      - 6000:3000
    state: started
  when: deploy_env == "stable"
  ignore_errors: True

- name: "Start the container for Beta"
  become: True
  docker_container:
    name: test_beta
    image: "erchiragjain92/node-test-app:beta"
    ports:
      - 6001:3000
    state: started
  when: deploy_env == "beta"
  ignore_errors: True
