- name: "Start the container for Production"
  become: True
  docker_container:
    name: latest
    image: "erchiragjain92/node-test-app:latest"
    ports:
      - 5000:3000
    state: started
  when: deploy_env == "stable"
  ignore_errors: True

- name: "Start the container for Beta"
  become: True
  docker_container:
    name: beta
    image: "erchiragjain92/node-test-app:beta"
    ports:
      - 5001:3000
    state: started
  when: deploy_env == "beta"
  ignore_errors: True
