- name: Start the container
  become: True
  docker_container:
    name: "{{ build_env }}"
    image: "erchiragjain92/node-test-app:{{ build_env }}"
    ports:
      - 5001:5000
    state: started
  ignore_errors: True
